name: Allowlist pool

on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        description: Network
        required: true
        options:
          - mainnet
          - polygon
          - arbitrum
          - gnosis-chain
      poolType:
        type: choice
        description: Pool Type
        required: true
        options:
          - Weighted
          - Stable
      poolId:
        type: string
        description: Pool ID
        required: true
      poolDescription:
        type: string
        description: Pool Description
        required: false

jobs:
  allowlist-pool:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install deps
        run: npm install cac
      - name: Run allowlist script
        run: npx vite-node ./src/lib/scripts/automatic-prs/allowlist-pool.ts --network ${{github.event.inputs.network}} --poolType ${{github.event.inputs.poolType}} --poolId \"${{github.event.inputs.poolId}}\" --poolDescription "${{github.event.inputs.poolDescription}}"
      - name: Run eslint fix of updated config files
        run: npm run lint:fix:config
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Update allowlist'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-allowlist
          base: master
          delete-branch: true
          title: 'Update pool allowlist'
          body: |
            This PR was autogenerated by the allowlist manual Github action.
          draft: false
          labels: allowlist
