# Bumps the package version with a patch if the version wasn't already updated
# - This is skipped if there is already a version bump in the merged PR
# Tags each push to master with version in package.json if not already a tag.
name: BumpTag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: 'timjrobinson/gh-action-bump-version@master'
      env:
        INPUT_COMMIT-MESSAGE: '^[0-9]+\.[0-9]+\.[0-9]+$' # Ignore bump if one of the new commits is a version bump (e.g. 1.101.0)
    - uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
