# Bumps the package version with a patch if the version wasn't already updated
# - This is skipped if there is already a version bump in the merged PR
# Tags each push to master with version in package.json if not already a tag.
name: BumpTag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: 'phips28/gh-action-bump-version@v9.1.3'
      with:
        commit-message: '{{version}}'
        GITHUB_TOKEN: '${{ secrets.TIM_PAT_TOKEN }}'
    - uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git branch -f deploy
        git push -f origin deploy
