# Bumps the package version with a patch if the version wasn't already updated
# - This is skipped if there is already a version bump in the merged PR
# Tags each push to master with version in package.json if not already a tag.
name: BumpTag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Bump version
        uses: 'phips28/gh-action-bump-version@v9.1.3'
        with:
          commit-message: '{{version}}'
          minor-wording: null
          major-wording: null
        env:
          GITHUB_TOKEN: ${{ secrets.TIM_PAT_TOKEN }}
      - name: Create tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/checkout@v3
      - name: Push to deploy branch
        shell: bash
        run: |
          [[ $(git log -1 --oneline) =~ ^.*([0-9]+\.[0-9]+\.[0-9]+)$ ]] || exit 0
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git branch -f deploy
          git push -f origin deploy
